### ISSUE TITLE
Consider using unix time instead of local time

### ISSUE THREAD

**Issue by MCWertGaming** [MyFursona-Project/sofox#1]
See https://github.com/Project-Sparrow/foxbow/pull/5#discussion_r990499036 for details.

**Comment by Relms12345** [comment]
The main reason why i decided to bring up how we store timestampes in the first place is because I wanna try and prevent the pain as seen in https://www.youtube.com/watch?v=-5wpm-gesOY as much as possible

**Comment by MCWertGaming** [comment]
the cool thing about Time.time is that you can convert it into whatever you want to. So we just need to send a UTC unix timestamp through the json, then the front-end puts the browsers timezone on-top of it.

**Comment by MCWertGaming** [comment]
Shouldn't be hard, GO is really good on those things, same with full UTF8 support out-of-the-box, but we'll test it ^^

**Comment by MCWertGaming** [comment]
We are using [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).
